services:
  - type: web
    name: eshop-django-app
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r e_shop/requirements.txt
    startCommand: cd e_shop && ./startup.sh
    envVarGroups:
      - key: django-settings
    domains:
      - eshop-django-app.onrender.com
